package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBCallAlarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.main_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer mainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.alarm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer alarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.alarm_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String alarmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.var_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.var_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String varBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.time_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date timeBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_alarm.time_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date timeBak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.main_id
     *
     * @return the value of s_b_call_alarm.main_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.main_id
     *
     * @param mainId the value for s_b_call_alarm.main_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.alarm_id
     *
     * @return the value of s_b_call_alarm.alarm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.alarm_id
     *
     * @param alarmId the value for s_b_call_alarm.alarm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setAlarmId(Integer alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.alarm_code
     *
     * @return the value of s_b_call_alarm.alarm_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getAlarmCode() {
        return alarmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.alarm_code
     *
     * @param alarmCode the value for s_b_call_alarm.alarm_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setAlarmCode(String alarmCode) {
        this.alarmCode = alarmCode == null ? null : alarmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.create_time
     *
     * @return the value of s_b_call_alarm.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.create_time
     *
     * @param createTime the value for s_b_call_alarm.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.modify_time
     *
     * @return the value of s_b_call_alarm.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.modify_time
     *
     * @param modifyTime the value for s_b_call_alarm.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.var_bak1
     *
     * @return the value of s_b_call_alarm.var_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.var_bak1
     *
     * @param varBak1 the value for s_b_call_alarm.var_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.var_bak2
     *
     * @return the value of s_b_call_alarm.var_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.var_bak2
     *
     * @param varBak2 the value for s_b_call_alarm.var_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.time_bak1
     *
     * @return the value of s_b_call_alarm.time_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getTimeBak1() {
        return timeBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.time_bak1
     *
     * @param timeBak1 the value for s_b_call_alarm.time_bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setTimeBak1(Date timeBak1) {
        this.timeBak1 = timeBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_alarm.time_bak2
     *
     * @return the value of s_b_call_alarm.time_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getTimeBak2() {
        return timeBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_alarm.time_bak2
     *
     * @param timeBak2 the value for s_b_call_alarm.time_bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setTimeBak2(Date timeBak2) {
        this.timeBak2 = timeBak2;
    }
}