package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBCallDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.main_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Integer mainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.call_order
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Integer callOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.biz_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.user_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.phone_num
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.call_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date callTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.call_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String callResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.dayu_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String dayuResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.result_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date resultTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.create_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.modify_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.var_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.var_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private String varBak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.time_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date timeBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_detail.time_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    private Date timeBak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.main_id
     *
     * @return the value of s_b_call_detail.main_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.main_id
     *
     * @param mainId the value for s_b_call_detail.main_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.call_order
     *
     * @return the value of s_b_call_detail.call_order
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Integer getCallOrder() {
        return callOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.call_order
     *
     * @param callOrder the value for s_b_call_detail.call_order
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setCallOrder(Integer callOrder) {
        this.callOrder = callOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.biz_id
     *
     * @return the value of s_b_call_detail.biz_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.biz_id
     *
     * @param bizId the value for s_b_call_detail.biz_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.user_id
     *
     * @return the value of s_b_call_detail.user_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.user_id
     *
     * @param userId the value for s_b_call_detail.user_id
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.phone_num
     *
     * @return the value of s_b_call_detail.phone_num
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.phone_num
     *
     * @param phoneNum the value for s_b_call_detail.phone_num
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.call_time
     *
     * @return the value of s_b_call_detail.call_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.call_time
     *
     * @param callTime the value for s_b_call_detail.call_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setCallTime(Date callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.call_result
     *
     * @return the value of s_b_call_detail.call_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getCallResult() {
        return callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.call_result
     *
     * @param callResult the value for s_b_call_detail.call_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setCallResult(String callResult) {
        this.callResult = callResult == null ? null : callResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.dayu_result
     *
     * @return the value of s_b_call_detail.dayu_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getDayuResult() {
        return dayuResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.dayu_result
     *
     * @param dayuResult the value for s_b_call_detail.dayu_result
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setDayuResult(String dayuResult) {
        this.dayuResult = dayuResult == null ? null : dayuResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.result_time
     *
     * @return the value of s_b_call_detail.result_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getResultTime() {
        return resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.result_time
     *
     * @param resultTime the value for s_b_call_detail.result_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setResultTime(Date resultTime) {
        this.resultTime = resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.create_time
     *
     * @return the value of s_b_call_detail.create_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.create_time
     *
     * @param createTime the value for s_b_call_detail.create_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.modify_time
     *
     * @return the value of s_b_call_detail.modify_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.modify_time
     *
     * @param modifyTime the value for s_b_call_detail.modify_time
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.var_bak1
     *
     * @return the value of s_b_call_detail.var_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.var_bak1
     *
     * @param varBak1 the value for s_b_call_detail.var_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.var_bak2
     *
     * @return the value of s_b_call_detail.var_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.var_bak2
     *
     * @param varBak2 the value for s_b_call_detail.var_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.time_bak1
     *
     * @return the value of s_b_call_detail.time_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getTimeBak1() {
        return timeBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.time_bak1
     *
     * @param timeBak1 the value for s_b_call_detail.time_bak1
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setTimeBak1(Date timeBak1) {
        this.timeBak1 = timeBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_detail.time_bak2
     *
     * @return the value of s_b_call_detail.time_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public Date getTimeBak2() {
        return timeBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_detail.time_bak2
     *
     * @param timeBak2 the value for s_b_call_detail.time_bak2
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    public void setTimeBak2(Date timeBak2) {
        this.timeBak2 = timeBak2;
    }
}