package com.mtc.zljk.Alidayu.entity;

import java.math.BigDecimal;

public class SBExtremeAlarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.farm_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.house_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.breed_name
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer breedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.alarm_type
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.min_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer minMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.max_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer maxMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.min_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer minAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.max_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private Integer maxAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.low_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private BigDecimal lowAlarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.high_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private BigDecimal highAlarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.tar_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private BigDecimal tarAlarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.num_bak1
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private BigDecimal numBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_extreme_alarm.num_bak2
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    private BigDecimal numBak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.id
     *
     * @return the value of s_b_extreme_alarm.id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.id
     *
     * @param id the value for s_b_extreme_alarm.id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.farm_id
     *
     * @return the value of s_b_extreme_alarm.farm_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.farm_id
     *
     * @param farmId the value for s_b_extreme_alarm.farm_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.house_id
     *
     * @return the value of s_b_extreme_alarm.house_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.house_id
     *
     * @param houseId the value for s_b_extreme_alarm.house_id
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.breed_name
     *
     * @return the value of s_b_extreme_alarm.breed_name
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getBreedName() {
        return breedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.breed_name
     *
     * @param breedName the value for s_b_extreme_alarm.breed_name
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setBreedName(Integer breedName) {
        this.breedName = breedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.alarm_type
     *
     * @return the value of s_b_extreme_alarm.alarm_type
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.alarm_type
     *
     * @param alarmType the value for s_b_extreme_alarm.alarm_type
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setAlarmType(Integer alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.min_month
     *
     * @return the value of s_b_extreme_alarm.min_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getMinMonth() {
        return minMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.min_month
     *
     * @param minMonth the value for s_b_extreme_alarm.min_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setMinMonth(Integer minMonth) {
        this.minMonth = minMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.max_month
     *
     * @return the value of s_b_extreme_alarm.max_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getMaxMonth() {
        return maxMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.max_month
     *
     * @param maxMonth the value for s_b_extreme_alarm.max_month
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setMaxMonth(Integer maxMonth) {
        this.maxMonth = maxMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.min_age
     *
     * @return the value of s_b_extreme_alarm.min_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getMinAge() {
        return minAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.min_age
     *
     * @param minAge the value for s_b_extreme_alarm.min_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.max_age
     *
     * @return the value of s_b_extreme_alarm.max_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public Integer getMaxAge() {
        return maxAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.max_age
     *
     * @param maxAge the value for s_b_extreme_alarm.max_age
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.low_alarm
     *
     * @return the value of s_b_extreme_alarm.low_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public BigDecimal getLowAlarm() {
        return lowAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.low_alarm
     *
     * @param lowAlarm the value for s_b_extreme_alarm.low_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setLowAlarm(BigDecimal lowAlarm) {
        this.lowAlarm = lowAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.high_alarm
     *
     * @return the value of s_b_extreme_alarm.high_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public BigDecimal getHighAlarm() {
        return highAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.high_alarm
     *
     * @param highAlarm the value for s_b_extreme_alarm.high_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setHighAlarm(BigDecimal highAlarm) {
        this.highAlarm = highAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.tar_alarm
     *
     * @return the value of s_b_extreme_alarm.tar_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public BigDecimal getTarAlarm() {
        return tarAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.tar_alarm
     *
     * @param tarAlarm the value for s_b_extreme_alarm.tar_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setTarAlarm(BigDecimal tarAlarm) {
        this.tarAlarm = tarAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.num_bak1
     *
     * @return the value of s_b_extreme_alarm.num_bak1
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public BigDecimal getNumBak1() {
        return numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.num_bak1
     *
     * @param numBak1 the value for s_b_extreme_alarm.num_bak1
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setNumBak1(BigDecimal numBak1) {
        this.numBak1 = numBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_extreme_alarm.num_bak2
     *
     * @return the value of s_b_extreme_alarm.num_bak2
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public BigDecimal getNumBak2() {
        return numBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_extreme_alarm.num_bak2
     *
     * @param numBak2 the value for s_b_extreme_alarm.num_bak2
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    public void setNumBak2(BigDecimal numBak2) {
        this.numBak2 = numBak2;
    }
}