package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBRemindSwitch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer remindMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.status
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_switch.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.farm_id
     *
     * @return the value of s_b_remind_switch.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.farm_id
     *
     * @param farmId the value for s_b_remind_switch.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.house_id
     *
     * @return the value of s_b_remind_switch.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.house_id
     *
     * @param houseId the value for s_b_remind_switch.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.remind_method
     *
     * @return the value of s_b_remind_switch.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getRemindMethod() {
        return remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.remind_method
     *
     * @param remindMethod the value for s_b_remind_switch.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setRemindMethod(Integer remindMethod) {
        this.remindMethod = remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.status
     *
     * @return the value of s_b_remind_switch.status
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.status
     *
     * @param status the value for s_b_remind_switch.status
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.create_time
     *
     * @return the value of s_b_remind_switch.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.create_time
     *
     * @param createTime the value for s_b_remind_switch.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.create_person
     *
     * @return the value of s_b_remind_switch.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.create_person
     *
     * @param createPerson the value for s_b_remind_switch.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.modify_person
     *
     * @return the value of s_b_remind_switch.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.modify_person
     *
     * @param modifyPerson the value for s_b_remind_switch.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_switch.modify_time
     *
     * @return the value of s_b_remind_switch.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_switch.modify_time
     *
     * @param modifyTime the value for s_b_remind_switch.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}