package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBRemindSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer remindMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.switch_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String switchReleHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.person_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String personReleHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.alarm_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String alarmReleHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_remind_setting.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.farm_id
     *
     * @return the value of s_b_remind_setting.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.farm_id
     *
     * @param farmId the value for s_b_remind_setting.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.remind_method
     *
     * @return the value of s_b_remind_setting.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getRemindMethod() {
        return remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.remind_method
     *
     * @param remindMethod the value for s_b_remind_setting.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setRemindMethod(Integer remindMethod) {
        this.remindMethod = remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.switch_rele_house
     *
     * @return the value of s_b_remind_setting.switch_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getSwitchReleHouse() {
        return switchReleHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.switch_rele_house
     *
     * @param switchReleHouse the value for s_b_remind_setting.switch_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setSwitchReleHouse(String switchReleHouse) {
        this.switchReleHouse = switchReleHouse == null ? null : switchReleHouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.person_rele_house
     *
     * @return the value of s_b_remind_setting.person_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getPersonReleHouse() {
        return personReleHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.person_rele_house
     *
     * @param personReleHouse the value for s_b_remind_setting.person_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setPersonReleHouse(String personReleHouse) {
        this.personReleHouse = personReleHouse == null ? null : personReleHouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.alarm_rele_house
     *
     * @return the value of s_b_remind_setting.alarm_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getAlarmReleHouse() {
        return alarmReleHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.alarm_rele_house
     *
     * @param alarmReleHouse the value for s_b_remind_setting.alarm_rele_house
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setAlarmReleHouse(String alarmReleHouse) {
        this.alarmReleHouse = alarmReleHouse == null ? null : alarmReleHouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.create_time
     *
     * @return the value of s_b_remind_setting.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.create_time
     *
     * @param createTime the value for s_b_remind_setting.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.bak1
     *
     * @return the value of s_b_remind_setting.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.bak1
     *
     * @param bak1 the value for s_b_remind_setting.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_remind_setting.bak2
     *
     * @return the value of s_b_remind_setting.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_remind_setting.bak2
     *
     * @param bak2 the value for s_b_remind_setting.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }
}