package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SDTtsTempParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_temp_param.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String tempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_temp_param.param_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_temp_param.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_temp_param.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_temp_param.temp_id
     *
     * @return the value of s_d_tts_temp_param.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_temp_param.temp_id
     *
     * @param tempId the value for s_d_tts_temp_param.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setTempId(String tempId) {
        this.tempId = tempId == null ? null : tempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_temp_param.param_name
     *
     * @return the value of s_d_tts_temp_param.param_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_temp_param.param_name
     *
     * @param paramName the value for s_d_tts_temp_param.param_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_temp_param.description
     *
     * @return the value of s_d_tts_temp_param.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_temp_param.description
     *
     * @param description the value for s_d_tts_temp_param.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_temp_param.create_time
     *
     * @return the value of s_d_tts_temp_param.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_temp_param.create_time
     *
     * @param createTime the value for s_d_tts_temp_param.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}