package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SDTtsTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String tempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.bill_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.temp_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String tempName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.var_bak1
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String varBak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_tts_template.var_bak2
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    private String varBak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.temp_id
     *
     * @return the value of s_d_tts_template.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.temp_id
     *
     * @param tempId the value for s_d_tts_template.temp_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setTempId(String tempId) {
        this.tempId = tempId == null ? null : tempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.bill_id
     *
     * @return the value of s_d_tts_template.bill_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.bill_id
     *
     * @param billId the value for s_d_tts_template.bill_id
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.temp_name
     *
     * @return the value of s_d_tts_template.temp_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getTempName() {
        return tempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.temp_name
     *
     * @param tempName the value for s_d_tts_template.temp_name
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setTempName(String tempName) {
        this.tempName = tempName == null ? null : tempName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.create_time
     *
     * @return the value of s_d_tts_template.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.create_time
     *
     * @param createTime the value for s_d_tts_template.create_time
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.description
     *
     * @return the value of s_d_tts_template.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.description
     *
     * @param description the value for s_d_tts_template.description
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.var_bak1
     *
     * @return the value of s_d_tts_template.var_bak1
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getVarBak1() {
        return varBak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.var_bak1
     *
     * @param varBak1 the value for s_d_tts_template.var_bak1
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setVarBak1(String varBak1) {
        this.varBak1 = varBak1 == null ? null : varBak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_tts_template.var_bak2
     *
     * @return the value of s_d_tts_template.var_bak2
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public String getVarBak2() {
        return varBak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_tts_template.var_bak2
     *
     * @param varBak2 the value for s_d_tts_template.var_bak2
     *
     * @mbggenerated Mon Jul 04 11:20:00 CST 2016
     */
    public void setVarBak2(String varBak2) {
        this.varBak2 = varBak2 == null ? null : varBak2.trim();
    }
}