package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SLDayuTtsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.biz_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.called_num
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String calledNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.temp_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String tempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.temp_param
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String tempParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.called_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date calledTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.sub_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String subCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.request_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.status_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.duration
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.start_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.end_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.status_msg
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String statusMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.extend
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_l_dayu_tts_log.bak3
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.biz_id
     *
     * @return the value of s_l_dayu_tts_log.biz_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.biz_id
     *
     * @param bizId the value for s_l_dayu_tts_log.biz_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.called_num
     *
     * @return the value of s_l_dayu_tts_log.called_num
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getCalledNum() {
        return calledNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.called_num
     *
     * @param calledNum the value for s_l_dayu_tts_log.called_num
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCalledNum(String calledNum) {
        this.calledNum = calledNum == null ? null : calledNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.temp_id
     *
     * @return the value of s_l_dayu_tts_log.temp_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.temp_id
     *
     * @param tempId the value for s_l_dayu_tts_log.temp_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setTempId(String tempId) {
        this.tempId = tempId == null ? null : tempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.temp_param
     *
     * @return the value of s_l_dayu_tts_log.temp_param
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getTempParam() {
        return tempParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.temp_param
     *
     * @param tempParam the value for s_l_dayu_tts_log.temp_param
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setTempParam(String tempParam) {
        this.tempParam = tempParam == null ? null : tempParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.called_time
     *
     * @return the value of s_l_dayu_tts_log.called_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCalledTime() {
        return calledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.called_time
     *
     * @param calledTime the value for s_l_dayu_tts_log.called_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCalledTime(Date calledTime) {
        this.calledTime = calledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.sub_code
     *
     * @return the value of s_l_dayu_tts_log.sub_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getSubCode() {
        return subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.sub_code
     *
     * @param subCode the value for s_l_dayu_tts_log.sub_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setSubCode(String subCode) {
        this.subCode = subCode == null ? null : subCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.request_id
     *
     * @return the value of s_l_dayu_tts_log.request_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.request_id
     *
     * @param requestId the value for s_l_dayu_tts_log.request_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.status_code
     *
     * @return the value of s_l_dayu_tts_log.status_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.status_code
     *
     * @param statusCode the value for s_l_dayu_tts_log.status_code
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.duration
     *
     * @return the value of s_l_dayu_tts_log.duration
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.duration
     *
     * @param duration the value for s_l_dayu_tts_log.duration
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.start_time
     *
     * @return the value of s_l_dayu_tts_log.start_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.start_time
     *
     * @param startTime the value for s_l_dayu_tts_log.start_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.end_time
     *
     * @return the value of s_l_dayu_tts_log.end_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.end_time
     *
     * @param endTime the value for s_l_dayu_tts_log.end_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.status_msg
     *
     * @return the value of s_l_dayu_tts_log.status_msg
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.status_msg
     *
     * @param statusMsg the value for s_l_dayu_tts_log.status_msg
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg == null ? null : statusMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.extend
     *
     * @return the value of s_l_dayu_tts_log.extend
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.extend
     *
     * @param extend the value for s_l_dayu_tts_log.extend
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.create_time
     *
     * @return the value of s_l_dayu_tts_log.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.create_time
     *
     * @param createTime the value for s_l_dayu_tts_log.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.modify_time
     *
     * @return the value of s_l_dayu_tts_log.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.modify_time
     *
     * @param modifyTime the value for s_l_dayu_tts_log.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.bak1
     *
     * @return the value of s_l_dayu_tts_log.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.bak1
     *
     * @param bak1 the value for s_l_dayu_tts_log.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.bak2
     *
     * @return the value of s_l_dayu_tts_log.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.bak2
     *
     * @param bak2 the value for s_l_dayu_tts_log.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_l_dayu_tts_log.bak3
     *
     * @return the value of s_l_dayu_tts_log.bak3
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_l_dayu_tts_log.bak3
     *
     * @param bak3 the value for s_l_dayu_tts_log.bak3
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}