package com.mtc.zljk.Alidayu.entity.mapper;

import com.mtc.zljk.Alidayu.entity.SBCallMain;
import java.util.List;

public interface SBCallMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    int insert(SBCallMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    SBCallMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    List<SBCallMain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    int updateByPrimaryKey(SBCallMain record);
}