package com.mtc.zljk.Alidayu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SDFarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_code
     *
     * @mbggenerated
     */
    private String farmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_name_chs
     *
     * @mbggenerated
     */
    private String farmNameChs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_name_en
     *
     * @mbggenerated
     */
    private String farmNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.feed_method
     *
     * @mbggenerated
     */
    private String feedMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.layers
     *
     * @mbggenerated
     */
    private Integer layers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.rows
     *
     * @mbggenerated
     */
    private Integer rows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.feed_density
     *
     * @mbggenerated
     */
    private BigDecimal feedDensity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.h_length
     *
     * @mbggenerated
     */
    private BigDecimal hLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.h_width
     *
     * @mbggenerated
     */
    private BigDecimal hWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.h_height
     *
     * @mbggenerated
     */
    private BigDecimal hHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.corporation
     *
     * @mbggenerated
     */
    private String corporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_add1
     *
     * @mbggenerated
     */
    private String farmAdd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_add2
     *
     * @mbggenerated
     */
    private String farmAdd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_add3
     *
     * @mbggenerated
     */
    private String farmAdd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_add4
     *
     * @mbggenerated
     */
    private String farmAdd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.farm_add5
     *
     * @mbggenerated
     */
    private String farmAdd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_1
     *
     * @mbggenerated
     */
    private String memo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_2
     *
     * @mbggenerated
     */
    private String memo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.freeze_status
     *
     * @mbggenerated
     */
    private String freezeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.create_person
     *
     * @mbggenerated
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.modify_person
     *
     * @mbggenerated
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.corporation2
     *
     * @mbggenerated
     */
    private String corporation2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_3
     *
     * @mbggenerated
     */
    private String memo3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_4
     *
     * @mbggenerated
     */
    private String memo4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_5
     *
     * @mbggenerated
     */
    private String memo5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_d_farm.memo_6
     *
     * @mbggenerated
     */
    private String memo6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.id
     *
     * @return the value of s_d_farm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.id
     *
     * @param id the value for s_d_farm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_code
     *
     * @return the value of s_d_farm.farm_code
     *
     * @mbggenerated
     */
    public String getFarmCode() {
        return farmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_code
     *
     * @param farmCode the value for s_d_farm.farm_code
     *
     * @mbggenerated
     */
    public void setFarmCode(String farmCode) {
        this.farmCode = farmCode == null ? null : farmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_name_chs
     *
     * @return the value of s_d_farm.farm_name_chs
     *
     * @mbggenerated
     */
    public String getFarmNameChs() {
        return farmNameChs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_name_chs
     *
     * @param farmNameChs the value for s_d_farm.farm_name_chs
     *
     * @mbggenerated
     */
    public void setFarmNameChs(String farmNameChs) {
        this.farmNameChs = farmNameChs == null ? null : farmNameChs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_name_en
     *
     * @return the value of s_d_farm.farm_name_en
     *
     * @mbggenerated
     */
    public String getFarmNameEn() {
        return farmNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_name_en
     *
     * @param farmNameEn the value for s_d_farm.farm_name_en
     *
     * @mbggenerated
     */
    public void setFarmNameEn(String farmNameEn) {
        this.farmNameEn = farmNameEn == null ? null : farmNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.feed_method
     *
     * @return the value of s_d_farm.feed_method
     *
     * @mbggenerated
     */
    public String getFeedMethod() {
        return feedMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.feed_method
     *
     * @param feedMethod the value for s_d_farm.feed_method
     *
     * @mbggenerated
     */
    public void setFeedMethod(String feedMethod) {
        this.feedMethod = feedMethod == null ? null : feedMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.layers
     *
     * @return the value of s_d_farm.layers
     *
     * @mbggenerated
     */
    public Integer getLayers() {
        return layers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.layers
     *
     * @param layers the value for s_d_farm.layers
     *
     * @mbggenerated
     */
    public void setLayers(Integer layers) {
        this.layers = layers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.rows
     *
     * @return the value of s_d_farm.rows
     *
     * @mbggenerated
     */
    public Integer getRows() {
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.rows
     *
     * @param rows the value for s_d_farm.rows
     *
     * @mbggenerated
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.feed_density
     *
     * @return the value of s_d_farm.feed_density
     *
     * @mbggenerated
     */
    public BigDecimal getFeedDensity() {
        return feedDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.feed_density
     *
     * @param feedDensity the value for s_d_farm.feed_density
     *
     * @mbggenerated
     */
    public void setFeedDensity(BigDecimal feedDensity) {
        this.feedDensity = feedDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.h_length
     *
     * @return the value of s_d_farm.h_length
     *
     * @mbggenerated
     */
    public BigDecimal gethLength() {
        return hLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.h_length
     *
     * @param hLength the value for s_d_farm.h_length
     *
     * @mbggenerated
     */
    public void sethLength(BigDecimal hLength) {
        this.hLength = hLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.h_width
     *
     * @return the value of s_d_farm.h_width
     *
     * @mbggenerated
     */
    public BigDecimal gethWidth() {
        return hWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.h_width
     *
     * @param hWidth the value for s_d_farm.h_width
     *
     * @mbggenerated
     */
    public void sethWidth(BigDecimal hWidth) {
        this.hWidth = hWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.h_height
     *
     * @return the value of s_d_farm.h_height
     *
     * @mbggenerated
     */
    public BigDecimal gethHeight() {
        return hHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.h_height
     *
     * @param hHeight the value for s_d_farm.h_height
     *
     * @mbggenerated
     */
    public void sethHeight(BigDecimal hHeight) {
        this.hHeight = hHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.corporation
     *
     * @return the value of s_d_farm.corporation
     *
     * @mbggenerated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.corporation
     *
     * @param corporation the value for s_d_farm.corporation
     *
     * @mbggenerated
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_add1
     *
     * @return the value of s_d_farm.farm_add1
     *
     * @mbggenerated
     */
    public String getFarmAdd1() {
        return farmAdd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_add1
     *
     * @param farmAdd1 the value for s_d_farm.farm_add1
     *
     * @mbggenerated
     */
    public void setFarmAdd1(String farmAdd1) {
        this.farmAdd1 = farmAdd1 == null ? null : farmAdd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_add2
     *
     * @return the value of s_d_farm.farm_add2
     *
     * @mbggenerated
     */
    public String getFarmAdd2() {
        return farmAdd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_add2
     *
     * @param farmAdd2 the value for s_d_farm.farm_add2
     *
     * @mbggenerated
     */
    public void setFarmAdd2(String farmAdd2) {
        this.farmAdd2 = farmAdd2 == null ? null : farmAdd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_add3
     *
     * @return the value of s_d_farm.farm_add3
     *
     * @mbggenerated
     */
    public String getFarmAdd3() {
        return farmAdd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_add3
     *
     * @param farmAdd3 the value for s_d_farm.farm_add3
     *
     * @mbggenerated
     */
    public void setFarmAdd3(String farmAdd3) {
        this.farmAdd3 = farmAdd3 == null ? null : farmAdd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_add4
     *
     * @return the value of s_d_farm.farm_add4
     *
     * @mbggenerated
     */
    public String getFarmAdd4() {
        return farmAdd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_add4
     *
     * @param farmAdd4 the value for s_d_farm.farm_add4
     *
     * @mbggenerated
     */
    public void setFarmAdd4(String farmAdd4) {
        this.farmAdd4 = farmAdd4 == null ? null : farmAdd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.farm_add5
     *
     * @return the value of s_d_farm.farm_add5
     *
     * @mbggenerated
     */
    public String getFarmAdd5() {
        return farmAdd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.farm_add5
     *
     * @param farmAdd5 the value for s_d_farm.farm_add5
     *
     * @mbggenerated
     */
    public void setFarmAdd5(String farmAdd5) {
        this.farmAdd5 = farmAdd5 == null ? null : farmAdd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_1
     *
     * @return the value of s_d_farm.memo_1
     *
     * @mbggenerated
     */
    public String getMemo1() {
        return memo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_1
     *
     * @param memo1 the value for s_d_farm.memo_1
     *
     * @mbggenerated
     */
    public void setMemo1(String memo1) {
        this.memo1 = memo1 == null ? null : memo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_2
     *
     * @return the value of s_d_farm.memo_2
     *
     * @mbggenerated
     */
    public String getMemo2() {
        return memo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_2
     *
     * @param memo2 the value for s_d_farm.memo_2
     *
     * @mbggenerated
     */
    public void setMemo2(String memo2) {
        this.memo2 = memo2 == null ? null : memo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.freeze_status
     *
     * @return the value of s_d_farm.freeze_status
     *
     * @mbggenerated
     */
    public String getFreezeStatus() {
        return freezeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.freeze_status
     *
     * @param freezeStatus the value for s_d_farm.freeze_status
     *
     * @mbggenerated
     */
    public void setFreezeStatus(String freezeStatus) {
        this.freezeStatus = freezeStatus == null ? null : freezeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.create_person
     *
     * @return the value of s_d_farm.create_person
     *
     * @mbggenerated
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.create_person
     *
     * @param createPerson the value for s_d_farm.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.create_date
     *
     * @return the value of s_d_farm.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.create_date
     *
     * @param createDate the value for s_d_farm.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.create_time
     *
     * @return the value of s_d_farm.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.create_time
     *
     * @param createTime the value for s_d_farm.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.modify_person
     *
     * @return the value of s_d_farm.modify_person
     *
     * @mbggenerated
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.modify_person
     *
     * @param modifyPerson the value for s_d_farm.modify_person
     *
     * @mbggenerated
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.modify_date
     *
     * @return the value of s_d_farm.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.modify_date
     *
     * @param modifyDate the value for s_d_farm.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.modify_time
     *
     * @return the value of s_d_farm.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.modify_time
     *
     * @param modifyTime the value for s_d_farm.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.corporation2
     *
     * @return the value of s_d_farm.corporation2
     *
     * @mbggenerated
     */
    public String getCorporation2() {
        return corporation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.corporation2
     *
     * @param corporation2 the value for s_d_farm.corporation2
     *
     * @mbggenerated
     */
    public void setCorporation2(String corporation2) {
        this.corporation2 = corporation2 == null ? null : corporation2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_3
     *
     * @return the value of s_d_farm.memo_3
     *
     * @mbggenerated
     */
    public String getMemo3() {
        return memo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_3
     *
     * @param memo3 the value for s_d_farm.memo_3
     *
     * @mbggenerated
     */
    public void setMemo3(String memo3) {
        this.memo3 = memo3 == null ? null : memo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_4
     *
     * @return the value of s_d_farm.memo_4
     *
     * @mbggenerated
     */
    public String getMemo4() {
        return memo4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_4
     *
     * @param memo4 the value for s_d_farm.memo_4
     *
     * @mbggenerated
     */
    public void setMemo4(String memo4) {
        this.memo4 = memo4 == null ? null : memo4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_5
     *
     * @return the value of s_d_farm.memo_5
     *
     * @mbggenerated
     */
    public String getMemo5() {
        return memo5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_5
     *
     * @param memo5 the value for s_d_farm.memo_5
     *
     * @mbggenerated
     */
    public void setMemo5(String memo5) {
        this.memo5 = memo5 == null ? null : memo5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_d_farm.memo_6
     *
     * @return the value of s_d_farm.memo_6
     *
     * @mbggenerated
     */
    public String getMemo6() {
        return memo6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_d_farm.memo_6
     *
     * @param memo6 the value for s_d_farm.memo_6
     *
     * @mbggenerated
     */
    public void setMemo6(String memo6) {
        this.memo6 = memo6 == null ? null : memo6.trim();
    }
}