package com.mtc.zljk.Alidayu.entity.mapper;


import java.util.List;

import com.mtc.zljk.Alidayu.entity.SBCallMain;
import org.apache.ibatis.annotations.Param;

public interface SBCallMainMapperCustom {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SBCallMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SBCallMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SBCallMain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_main
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SBCallMain record);

	SBCallMain selectCallMainByParams(@Param("farmId") int farmId, @Param("houseId") int houseId, @Param("tempId") String tempId);

	List<SBCallMain> getNeedCallMainInfo();

	int updateSBCallMain(SBCallMain main);

	int updateSBCallMainCallTimes(SBCallMain main);
}