package com.mtc.zljk.Alidayu.entity.mapper;

import com.mtc.zljk.Alidayu.entity.SBCallDetail;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SBCallDetailMapperCustom {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(@Param("mainId") Integer mainId, @Param("callOrder") Integer callOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SBCallDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SBCallDetail selectByPrimaryKey(@Param("mainId") Integer mainId, @Param("callOrder") Integer callOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SBCallDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SBCallDetail record);

	int insertCallDetails(List<SBCallDetail> list);

	/**
	 * 获取最近一次的拨打记录
	 * @param mainId
	 * @return
	 */
	List<SBCallDetail> getSBCallDetail(@Param("mainId") int mainId);

	/**
	 * 获取摸个状态下的拨打记录
	 * @param mainId
	 * @param callResult
	 * @return
	 */
	List<SBCallDetail> getSBCallDetailByCallResult(@Param("mainId") int mainId, @Param("callResult") String callResult);
}