package com.mtc.zljk.Alidayu.entity.mapper;

import com.mtc.zljk.Alidayu.entity.SBExtremeAlarm;

import java.util.List;

public interface SBExtremeAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_extreme_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_extreme_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    int insert(SBExtremeAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_extreme_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    SBExtremeAlarm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_extreme_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    List<SBExtremeAlarm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_extreme_alarm
     *
     * @mbggenerated Thu Jul 07 13:56:30 CST 2016
     */
    int updateByPrimaryKey(SBExtremeAlarm record);
}