package com.mtc.zljk.Alidayu.entity.mapper;

import com.mtc.zljk.Alidayu.entity.SBReminder;

import java.util.List;

public interface SBReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SBReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SBReminder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SBReminder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SBReminder record);
}