package com.mtc.zljk.Alidayu.entity.mapper;


import com.mtc.zljk.Alidayu.entity.SLDayuTtsLog;

import java.util.List;

public interface SLDayuTtsLogMapperCustom {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_dayu_tts_log
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(String bizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_dayu_tts_log
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SLDayuTtsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_dayu_tts_log
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SLDayuTtsLog selectByPrimaryKey(String bizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_dayu_tts_log
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SLDayuTtsLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_l_dayu_tts_log
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SLDayuTtsLog record);
    
    int updateByBizId(SLDayuTtsLog record);

	SLDayuTtsLog getSLDayuTtsLogByBizId(String bizId);
}