package com.mtc.zljk.Alidayu.entity.mapper;

import java.util.List;

import com.mtc.zljk.Alidayu.entity.SBReminder;
import org.apache.ibatis.annotations.Param;


public interface SBReminderMapperCustom {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SBReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SBReminder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SBReminder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_reminder
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SBReminder record);
    
    int insertBatch(List<SBReminder> list);

	List<SBReminder> selectByFarmIdAndAlarmType(@Param("farmId") Integer farmId,
                                                @Param("remindMethod") Integer alarmType);

	List<SBReminder> selectByFarmIdAndAlarmTypeAndHouseId(@Param("farmId") Integer farmId, @Param("houseId") int houseId,
                                                          @Param("remindMethod") Integer alarmType);
	
	int deleteByFarmHouseType(@Param("farmId") int farmId, @Param("houseId") int houseId, @Param("remindMethod") int remindMethod);
}