package com.mtc.zljk.Alidayu.entity.mapper;



import com.mtc.zljk.Alidayu.entity.SDUser;

import java.util.List;

public interface SDUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user
     *
     * @mbggenerated
     */
    int insert(SDUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user
     *
     * @mbggenerated
     */
    SDUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user
     *
     * @mbggenerated
     */
    List<SDUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_d_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SDUser record);
}