package com.mtc.zljk.Alidayu.entity;


public class SBFarmAlarmerTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.farm_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.house_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.user_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.user_id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.user_level
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_farm_alarmer.alarm_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    private Integer alarmType;


    private String userName;
    
    private String phoneNum;
    
    
    public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.id
     *
     * @return the value of s_b_farm_alarmer.id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.id
     *
     * @param id the value for s_b_farm_alarmer.id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.farm_Id
     *
     * @return the value of s_b_farm_alarmer.farm_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.farm_Id
     *
     * @param farmId the value for s_b_farm_alarmer.farm_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.house_Id
     *
     * @return the value of s_b_farm_alarmer.house_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.house_Id
     *
     * @param houseId the value for s_b_farm_alarmer.house_Id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.user_type
     *
     * @return the value of s_b_farm_alarmer.user_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.user_type
     *
     * @param userType the value for s_b_farm_alarmer.user_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.user_id
     *
     * @return the value of s_b_farm_alarmer.user_id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.user_id
     *
     * @param userId the value for s_b_farm_alarmer.user_id
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.user_level
     *
     * @return the value of s_b_farm_alarmer.user_level
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.user_level
     *
     * @param userLevel the value for s_b_farm_alarmer.user_level
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_farm_alarmer.alarm_type
     *
     * @return the value of s_b_farm_alarmer.alarm_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public Integer getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_farm_alarmer.alarm_type
     *
     * @param alarmType the value for s_b_farm_alarmer.alarm_type
     *
     * @mbggenerated Tue Jun 28 09:55:38 CST 2016
     */
    public void setAlarmType(Integer alarmType) {
        this.alarmType = alarmType;
    }

}