package com.mtc.zljk.Alidayu.entity.mapper;

import com.mtc.zljk.Alidayu.entity.SBCallDetail;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SBCallDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    int deleteByPrimaryKey(@Param("mainId") Integer mainId, @Param("callOrder") Integer callOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    int insert(SBCallDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    SBCallDetail selectByPrimaryKey(@Param("mainId") Integer mainId, @Param("callOrder") Integer callOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    List<SBCallDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_call_detail
     *
     * @mbggenerated Mon Jul 04 16:49:08 CST 2016
     */
    int updateByPrimaryKey(SBCallDetail record);
}