package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBCallMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.farm_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.house_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.temp_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private String tempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.call_result
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private String callResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.succ_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Date succTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.create_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.modify_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.bak1
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_call_main.bak2
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.id
     *
     * @return the value of s_b_call_main.id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.id
     *
     * @param id the value for s_b_call_main.id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.farm_id
     *
     * @return the value of s_b_call_main.farm_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.farm_id
     *
     * @param farmId the value for s_b_call_main.farm_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.house_id
     *
     * @return the value of s_b_call_main.house_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.house_id
     *
     * @param houseId the value for s_b_call_main.house_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.temp_id
     *
     * @return the value of s_b_call_main.temp_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public String getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.temp_id
     *
     * @param tempId the value for s_b_call_main.temp_id
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setTempId(String tempId) {
        this.tempId = tempId == null ? null : tempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.call_result
     *
     * @return the value of s_b_call_main.call_result
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public String getCallResult() {
        return callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.call_result
     *
     * @param callResult the value for s_b_call_main.call_result
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setCallResult(String callResult) {
        this.callResult = callResult == null ? null : callResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.succ_time
     *
     * @return the value of s_b_call_main.succ_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Date getSuccTime() {
        return succTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.succ_time
     *
     * @param succTime the value for s_b_call_main.succ_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setSuccTime(Date succTime) {
        this.succTime = succTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.create_time
     *
     * @return the value of s_b_call_main.create_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.create_time
     *
     * @param createTime the value for s_b_call_main.create_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.modify_time
     *
     * @return the value of s_b_call_main.modify_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.modify_time
     *
     * @param modifyTime the value for s_b_call_main.modify_time
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.bak1
     *
     * @return the value of s_b_call_main.bak1
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.bak1
     *
     * @param bak1 the value for s_b_call_main.bak1
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_call_main.bak2
     *
     * @return the value of s_b_call_main.bak2
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_call_main.bak2
     *
     * @param bak2 the value for s_b_call_main.bak2
     *
     * @mbggenerated Fri Jul 08 10:08:06 CST 2016
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }
}