package com.mtc.zljk.Alidayu.entity;

import java.util.Date;

public class SBReminder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.user_order
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer userOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer remindMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.user_type
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.user_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_reminder.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    private String bak2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.id
     *
     * @return the value of s_b_reminder.id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.id
     *
     * @param id the value for s_b_reminder.id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.user_order
     *
     * @return the value of s_b_reminder.user_order
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getUserOrder() {
        return userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.user_order
     *
     * @param userOrder the value for s_b_reminder.user_order
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setUserOrder(Integer userOrder) {
        this.userOrder = userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.remind_method
     *
     * @return the value of s_b_reminder.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getRemindMethod() {
        return remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.remind_method
     *
     * @param remindMethod the value for s_b_reminder.remind_method
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setRemindMethod(Integer remindMethod) {
        this.remindMethod = remindMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.farm_id
     *
     * @return the value of s_b_reminder.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.farm_id
     *
     * @param farmId the value for s_b_reminder.farm_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.house_id
     *
     * @return the value of s_b_reminder.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.house_id
     *
     * @param houseId the value for s_b_reminder.house_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.user_type
     *
     * @return the value of s_b_reminder.user_type
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.user_type
     *
     * @param userType the value for s_b_reminder.user_type
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.user_id
     *
     * @return the value of s_b_reminder.user_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.user_id
     *
     * @param userId the value for s_b_reminder.user_id
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.create_time
     *
     * @return the value of s_b_reminder.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.create_time
     *
     * @param createTime the value for s_b_reminder.create_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.create_person
     *
     * @return the value of s_b_reminder.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.create_person
     *
     * @param createPerson the value for s_b_reminder.create_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.modify_person
     *
     * @return the value of s_b_reminder.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.modify_person
     *
     * @param modifyPerson the value for s_b_reminder.modify_person
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.modify_time
     *
     * @return the value of s_b_reminder.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.modify_time
     *
     * @param modifyTime the value for s_b_reminder.modify_time
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.bak1
     *
     * @return the value of s_b_reminder.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.bak1
     *
     * @param bak1 the value for s_b_reminder.bak1
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_reminder.bak2
     *
     * @return the value of s_b_reminder.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_reminder.bak2
     *
     * @param bak2 the value for s_b_reminder.bak2
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }
}