package com.mtc.zljk.Alidayu.entity.mapper;

import java.util.List;

import com.mtc.zljk.Alidayu.entity.SBRemindSwitch;
import org.apache.ibatis.annotations.Param;

public interface SBRemindSwitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_remind_switch
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int deleteByPrimaryKey(@Param("farmId") Integer farmId, @Param("houseId") Integer houseId, @Param("remindMethod") Integer remindMethod);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_remind_switch
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int insert(SBRemindSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_remind_switch
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    SBRemindSwitch selectByPrimaryKey(@Param("farmId") Integer farmId, @Param("houseId") Integer houseId, @Param("remindMethod") Integer remindMethod);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_remind_switch
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    List<SBRemindSwitch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_b_remind_switch
     *
     * @mbggenerated Fri Jul 01 14:12:36 CST 2016
     */
    int updateByPrimaryKey(SBRemindSwitch record);
}